sudo: false
language: c
script: make
after_success: base64 bin/*
notifications:
  email: false
matrix:
  include:
    - os: linux
      compiler: gcc-5
      env: CFLAGS='-m32'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-5-multilib
    - os: linux
      compiler: gcc-5
      env: CFLAGS='-m64'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
    - os: linux
      compiler: clang-3.8
      env: CFLAGS='-target i686-linux-gnu'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - gcc-5-multilib
    - os: linux
      compiler: clang-3.8
      env: CFLAGS='-target x86_64-linux-gnu'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
    - os: linux
      compiler: clang-3.8
      env: CFLAGS='-target arm-linux-gnueabihf'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - gcc-multilib
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - os: osx
      compiler: clang-3.8
      env: CFLAGS='-target i686-apple-darwin'
      before_install:
        - brew update
        - brew install --with-clang llvm38
    - os: osx
      compiler: clang-3.8
      env: CFLAGS='-target x86_64-apple-darwin'
      before_install:
        - brew update
        - brew install --with-clang llvm38
