version: 2

workflows:
  version: 2
  build:
    jobs:
      - debian-stretch
      - macos-xcode-9.2:
          requires:
            - debian-stretch

jobs:
  debian-stretch:
    docker:
      - image: buildpack-deps:stretch-scm
    steps:
      - run:
          name: Install prerequisites
          command: |
            wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" > /etc/apt/sources.list.d/clang-5.0.list
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends clang-5.0 gcc-6 gcc-6-multilib make
      - checkout
      - run:
          name: Build (x64) (clang)
          command: |
            mkdir -p bin/x64/Release/0xf0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf0/clang/
            mkdir -p bin/x64/Release/0xe0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x64/Release/0xe0/clang/
            mkdir -p bin/x64/Release/0xd0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xd0/clang/
            mkdir -p bin/x64/Release/0xc0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xc0/clang/
            mkdir -p bin/x64/Release/0xb0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xb0/clang/
            mkdir -p bin/x64/Release/0xa0/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xa0/clang/
            mkdir -p bin/x64/Release/0x90/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x90/clang/
            mkdir -p bin/x64/Release/0x80/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x80/clang/
            mkdir -p bin/x64/Release/0x70/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x70/clang/
            mkdir -p bin/x64/Release/0x60/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x60/clang/
            mkdir -p bin/x64/Release/0x50/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x50/clang/
            mkdir -p bin/x64/Release/0x40/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x40/clang/
            mkdir -p bin/x64/Release/0x30/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x30/clang/
            mkdir -p bin/x64/Release/0x20/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x20/clang/
            mkdir -p bin/x64/Release/0x10/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x10/clang/
            mkdir -p bin/x64/Release/0x00/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x00/clang/
      - run:
          name: Build (x64) (gcc)
          command: |
            mkdir -p bin/x64/Release/0xf0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf0/gcc/
            mkdir -p bin/x64/Release/0xe0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x64/Release/0xe0/gcc/
            mkdir -p bin/x64/Release/0xd0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xd0/gcc/
            mkdir -p bin/x64/Release/0xc0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xc0/gcc/
            mkdir -p bin/x64/Release/0xb0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xb0/gcc/
            mkdir -p bin/x64/Release/0xa0/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xa0/gcc/
            mkdir -p bin/x64/Release/0x90/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x90/gcc/
            mkdir -p bin/x64/Release/0x80/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x80/gcc/
            mkdir -p bin/x64/Release/0x70/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x70/gcc/
            mkdir -p bin/x64/Release/0x60/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x60/gcc/
            mkdir -p bin/x64/Release/0x50/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x50/gcc/
            mkdir -p bin/x64/Release/0x40/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x40/gcc/
            mkdir -p bin/x64/Release/0x30/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x30/gcc/
            mkdir -p bin/x64/Release/0x20/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x20/gcc/
            mkdir -p bin/x64/Release/0x10/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x10/gcc/
            mkdir -p bin/x64/Release/0x00/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x00/gcc/
      - run:
          name: Build (x86) (clang)
          command: |
            mkdir -p bin/x86/Release/0xf0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG" PREFIX=bin/x86/Release/0xf0/clang/
            mkdir -p bin/x86/Release/0xe0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x86/Release/0xe0/clang/
            mkdir -p bin/x86/Release/0xd0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xd0/clang/
            mkdir -p bin/x86/Release/0xc0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xc0/clang/
            mkdir -p bin/x86/Release/0xb0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xb0/clang/
            mkdir -p bin/x86/Release/0xa0/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xa0/clang/
            mkdir -p bin/x86/Release/0x90/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x90/clang/
            mkdir -p bin/x86/Release/0x80/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x80/clang/
            mkdir -p bin/x86/Release/0x70/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x70/clang/
            mkdir -p bin/x86/Release/0x60/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x60/clang/
            mkdir -p bin/x86/Release/0x50/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x50/clang/
            mkdir -p bin/x86/Release/0x40/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x40/clang/
            mkdir -p bin/x86/Release/0x30/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x30/clang/
            mkdir -p bin/x86/Release/0x20/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x20/clang/
            mkdir -p bin/x86/Release/0x10/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x10/clang/
            mkdir -p bin/x86/Release/0x00/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x00/clang/
      - run:
          name: Build (x86) (gcc)
          command: |
            mkdir -p bin/x86/Release/0xf0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG" PREFIX=bin/x86/Release/0xf0/gcc/
            mkdir -p bin/x86/Release/0xe0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x86/Release/0xe0/gcc/
            mkdir -p bin/x86/Release/0xd0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xd0/gcc/
            mkdir -p bin/x86/Release/0xc0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xc0/gcc/
            mkdir -p bin/x86/Release/0xb0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xb0/gcc/
            mkdir -p bin/x86/Release/0xa0/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xa0/gcc/
            mkdir -p bin/x86/Release/0x90/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x90/gcc/
            mkdir -p bin/x86/Release/0x80/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x80/gcc/
            mkdir -p bin/x86/Release/0x70/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x70/gcc/
            mkdir -p bin/x86/Release/0x60/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x60/gcc/
            mkdir -p bin/x86/Release/0x50/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x50/gcc/
            mkdir -p bin/x86/Release/0x40/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x40/gcc/
            mkdir -p bin/x86/Release/0x30/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x30/gcc/
            mkdir -p bin/x86/Release/0x20/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x20/gcc/
            mkdir -p bin/x86/Release/0x10/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x10/gcc/
            mkdir -p bin/x86/Release/0x00/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x00/gcc/
      - store_artifacts:
          path: bin/x64/Release/0xf0/clang/
          destination: /linux-x64/
  macos-xcode-9.2:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Build (x64)
          command: |
            mkdir -p bin/x64/Release/0xf0/clang/ && make CC=clang CFLAGS="-target x86_64-apple-darwin -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf0/clang/
      - store_artifacts:
          path: bin/x64/Release/0xf0/clang/
          destination: /osx-x64/
