version: 2

workflows:
  version: 2
  build:
    jobs:
      - debian-stretch
      - macos-xcode-9.2:
          requires:
            - debian-stretch

jobs:
  debian-stretch:
    docker:
      - image: buildpack-deps:stretch-scm
    steps:
      - run:
          name: Install prerequisites
          command: |
            wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" > /etc/apt/sources.list.d/clang-5.0.list
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends clang-5.0 gcc-6 gcc-6-multilib make
      - checkout
      - run:
          name: Build (x64) (clang)
          command: |
            mkdir -p bin/x64/Release/0xf000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf000/clang/
            mkdir -p bin/x64/Release/0xe000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x64/Release/0xe000/clang/
            mkdir -p bin/x64/Release/0xd000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xd000/clang/
            mkdir -p bin/x64/Release/0xc000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xc000/clang/
            mkdir -p bin/x64/Release/0xb000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xb000/clang/
            mkdir -p bin/x64/Release/0xa000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xa000/clang/
            mkdir -p bin/x64/Release/0x9000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x9000/clang/
            mkdir -p bin/x64/Release/0x8000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x8000/clang/
            mkdir -p bin/x64/Release/0x7000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x7000/clang/
            mkdir -p bin/x64/Release/0x6000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x6000/clang/
            mkdir -p bin/x64/Release/0x5000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x5000/clang/
            mkdir -p bin/x64/Release/0x4000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x4000/clang/
            mkdir -p bin/x64/Release/0x3000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x3000/clang/
            mkdir -p bin/x64/Release/0x2000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x2000/clang/
            mkdir -p bin/x64/Release/0x1000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x1000/clang/
            mkdir -p bin/x64/Release/0x0000/clang/ && make CC=clang-5.0 CFLAGS="-target x86_64-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x0000/clang/
      - run:
          name: Build (x64) (gcc)
          command: |
            mkdir -p bin/x64/Release/0xf000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf000/gcc/
            mkdir -p bin/x64/Release/0xe000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x64/Release/0xe000/gcc/
            mkdir -p bin/x64/Release/0xd000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xd000/gcc/
            mkdir -p bin/x64/Release/0xc000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x64/Release/0xc000/gcc/
            mkdir -p bin/x64/Release/0xb000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xb000/gcc/
            mkdir -p bin/x64/Release/0xa000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0xa000/gcc/
            mkdir -p bin/x64/Release/0x9000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x9000/gcc/
            mkdir -p bin/x64/Release/0x8000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x64/Release/0x8000/gcc/
            mkdir -p bin/x64/Release/0x7000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x7000/gcc/
            mkdir -p bin/x64/Release/0x6000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x6000/gcc/
            mkdir -p bin/x64/Release/0x5000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x5000/gcc/
            mkdir -p bin/x64/Release/0x4000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x4000/gcc/
            mkdir -p bin/x64/Release/0x3000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x3000/gcc/
            mkdir -p bin/x64/Release/0x2000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x2000/gcc/
            mkdir -p bin/x64/Release/0x1000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x1000/gcc/
            mkdir -p bin/x64/Release/0x0000/gcc/ && make CC=gcc-6 CFLAGS="-m64 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x64/Release/0x0000/gcc/
      - run:
          name: Build (x86) (clang)
          command: |
            mkdir -p bin/x86/Release/0xf000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG" PREFIX=bin/x86/Release/0xf000/clang/
            mkdir -p bin/x86/Release/0xe000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x86/Release/0xe000/clang/
            mkdir -p bin/x86/Release/0xd000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xd000/clang/
            mkdir -p bin/x86/Release/0xc000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xc000/clang/
            mkdir -p bin/x86/Release/0xb000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xb000/clang/
            mkdir -p bin/x86/Release/0xa000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xa000/clang/
            mkdir -p bin/x86/Release/0x9000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x9000/clang/
            mkdir -p bin/x86/Release/0x8000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x8000/clang/
            mkdir -p bin/x86/Release/0x7000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x7000/clang/
            mkdir -p bin/x86/Release/0x6000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x6000/clang/
            mkdir -p bin/x86/Release/0x5000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x5000/clang/
            mkdir -p bin/x86/Release/0x4000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x4000/clang/
            mkdir -p bin/x86/Release/0x3000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x3000/clang/
            mkdir -p bin/x86/Release/0x2000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x2000/clang/
            mkdir -p bin/x86/Release/0x1000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x1000/clang/
            mkdir -p bin/x86/Release/0x0000/clang/ && make CC=clang-5.0 CFLAGS="-target i686-linux-gnu -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x0000/clang/
      - run:
          name: Build (x86) (gcc)
          command: |
            mkdir -p bin/x86/Release/0xf000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG" PREFIX=bin/x86/Release/0xf000/gcc/
            mkdir -p bin/x86/Release/0xe000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64" PREFIX=bin/x86/Release/0xe000/gcc/
            mkdir -p bin/x86/Release/0xd000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xd000/gcc/
            mkdir -p bin/x86/Release/0xc000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32" PREFIX=bin/x86/Release/0xc000/gcc/
            mkdir -p bin/x86/Release/0xb000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xb000/gcc/
            mkdir -p bin/x86/Release/0xa000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0xa000/gcc/
            mkdir -p bin/x86/Release/0x9000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x9000/gcc/
            mkdir -p bin/x86/Release/0x8000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64" PREFIX=bin/x86/Release/0x8000/gcc/
            mkdir -p bin/x86/Release/0x7000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x7000/gcc/
            mkdir -p bin/x86/Release/0x6000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x6000/gcc/
            mkdir -p bin/x86/Release/0x5000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x5000/gcc/
            mkdir -p bin/x86/Release/0x4000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x4000/gcc/
            mkdir -p bin/x86/Release/0x3000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x3000/gcc/
            mkdir -p bin/x86/Release/0x2000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x2000/gcc/
            mkdir -p bin/x86/Release/0x1000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x1000/gcc/
            mkdir -p bin/x86/Release/0x0000/gcc/ && make CC=gcc-6 CFLAGS="-m32 -O3 -DNDEBUG -DMANGO_NO_I64 -DMANGO_NO_F32 -DMANGO_NO_F64 -DMANGO_NO_REFS" PREFIX=bin/x86/Release/0x0000/gcc/
      - store_artifacts:
          path: bin/x64/Release/0xf000/clang/
          destination: /linux-x64/
  macos-xcode-9.2:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Build (x64)
          command: |
            mkdir -p bin/x64/Release/0xf000/clang/ && make CC=clang CFLAGS="-target x86_64-apple-darwin -O3 -DNDEBUG" PREFIX=bin/x64/Release/0xf000/clang/
      - store_artifacts:
          path: bin/x64/Release/0xf000/clang/
          destination: /osx-x64/
